### ISSUE TITLE
Compatability with Fabrics Armor Rendering API

### ISSUE THREAD

**Issue by Noaaan** [NyakoFox/VanitySlots#6]
Currently with the current Vanity Slots implementation there is no support for [Fabrics Armor Rendering API](https://github.com/FabricMC/fabric/blob/1.19.3/fabric-rendering-v1/src/client/java/net/fabricmc/fabric/api/client/rendering/v1/ArmorRenderer.java).
This means mods like Mythic Metals (see https://github.com/Noaaan/MythicMetals/issues/131) and Botania (see attached screenshot) breaks. 

An example of how this could be implemented would be from [Cosmetic Armor](https://github.com/apace100/cosmetic-armor/blob/1.19/src/main/java/io/github/apace100/cosmetic_armor/mixin/MixinCosmeticArmorVisibility.java).

![image](https://user-images.githubusercontent.com/4163353/207499573-68b09a38-47ec-49a5-b7c0-e06e3ef64746.png)

**Comment by NyakoFox** [comment]
Attempted to add support in 242dded9d87b38e0b19d21ecb6c60696395d15b6 (and a followup commit to adjust priority, whoops), but I'm unable to test due to Mythic Metals, Botania, MCDoom and Immersive Armors all being on 1.19.2, where this mod currently resides on 1.19.3. Once one of the mods updates, or I'm shown another mod which uses the API which exists on 1.19.3, I'll test and publish a new version of VanitySlots if everything goes correctly.

Thank you very much for bringing this to my attention -- I had no idea this API was a thing.

**Comment by NyakoFox** [comment]
I noticed bumblezone has a 1.19.3 version, and noticed some logic issues with my commit... I'll take a look at this tomorrow.

**Comment by NyakoFox** [comment]
I've now released 1.2.5 which should fix this issue once and for all!

**Comment by Noaaan** [comment]
Thank you for the quick fix! ❤
